### PR TITLE
📝 Remove Package.swift, add details to readme

### PR DESCRIPTION
**Pull request by phatblat**
We've decided to not bother with updating the `main` branch to simplify deployment of our SwiftPM package release. This PR removes the `Package.swift` file from the repo and adds details to the readme for how users can find more info. After this change, the `main` branch is effectively just a `README.md` for humans and a link to the [tags](https://github.com/getditto/DittoSwiftPackage/tags) page where new versions will show up.

Also, the link to our iOS installation docs was broken as the URL has changed recently.

### CODE REVIEW

**Comment by daveverwer** [comment]
Really sorry to resurrect an old PR with a new comment, but someone working with some new search functionality for the Swift Package Index came across the fact that the `Package.swift` file has been removed from this repo.

We rely really heavily on there being a `Package.swift` on the default branch to determine lots of the package metadata that we display on the package page. Removing one from a project that originally had one doesn't cause immediate problems, but we do remove packages that do this as they wouldn't pass validation if submitted in this state.

I'm writing a note here as it's going to break your SPI badges that you added to your README. We're thinking about ways to deal with this issue, but it's a situation that's quite tricky for us to cope with.

Hope it was OK to leave a note here!

**Comment by phatblat** [comment]
Thanks for the reminder! This has been brought up a few times and we're planning to resurrect it, just need our deployment to update the `main` branch instead of creating orphaned branches (which was a little easier).

**Comment by daveverwer** [comment]
Ah, that's great news! Thanks for the very quick reply!

I've removed it from the index for now, but please do feel free to re-add it as soon as there's a `Package.swift` file again.

**Comment by phatblat** [comment]
Created issue #16 to track

**Pull request merged**
